package com.tibco.bw.maven.plugin.packaging;

import com.tibco.bw.maven.plugin.tra.TraFile;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import java.io.File;
import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

/**
 * Tests for the project-local {@code bwengine.tra} generated by {@code bw5:run}.
 *
 * <p>The engine is launched with {@code --propFile target/.TIBCO/bwengine.tra} so the project can
 * adjust launcher settings without writing to the TIBCO installation. The installation is often
 * shared and read-only, so the goal must also keep working when no {@code bwengine.tra} can be
 * found next to the engine binary: before this feature the goal warned and started the engine
 * anyway, and it still has to.</p>
 */
public class RunBwMojoTraTest {

    @Rule
    public TemporaryFolder tmp = new TemporaryFolder();

    private static final List<String> BWENGINE_TRA = Arrays.asList(
        "# bwengine.tra",
        "tibco.env.TIB_HOME=/opt/tibco",
        "tibco.env.CUSTOM_EXT_PREPEND_CP=/opt/tibco/bw/5.16/hotfix/lib",
        "tibco.class.path.extended %CUSTOM_EXT_PREPEND_CP%:%STD_EXT_CP%");

    @Test
    public void copiesTheInstalledTraToTheBuildDirectory() throws Exception {
        File baseTra = tmp.newFile("bwengine.tra");
        TraFile.write(baseTra, BWENGINE_TRA);
        File out = new File(tmp.newFolder("target"), ".TIBCO/bwengine.tra");

        File generated = new RunBwMojo().prepareEngineTra(baseTra, out);

        assertNotNull("a copy must be generated when the installed tra exists", generated);
        assertEquals(out, generated);
        assertTrue("the copy must be written to disk", out.isFile());
        assertEquals("the copy must preserve the installed tra verbatim",
            BWENGINE_TRA, TraFile.read(out));
    }

    @Test
    public void createsTheTargetDirectoryWhenMissing() throws Exception {
        File baseTra = tmp.newFile("bwengine.tra");
        TraFile.write(baseTra, BWENGINE_TRA);
        File out = new File(tmp.getRoot(), "target/.TIBCO/bwengine.tra");
        assertFalse(out.getParentFile().exists());

        assertNotNull(new RunBwMojo().prepareEngineTra(baseTra, out));
        assertTrue(out.isFile());
    }

    /**
     * Degrading gracefully matters: the goal must not start failing on installations that have no
     * bwengine.tra next to the binary, which used to warn and run with the engine defaults.
     */
    @Test
    public void returnsNullAndWritesNothingWhenTheInstalledTraIsMissing() throws Exception {
        File baseTra = new File(tmp.getRoot(), "no-such-bwengine.tra");
        File out = new File(tmp.getRoot(), "target/.TIBCO/bwengine.tra");

        assertNull(new RunBwMojo().prepareEngineTra(baseTra, out));
        assertFalse("nothing may be written when there is no source tra", out.exists());
    }

    /** A stale copy from a previous run must be replaced, so installation hotfixes are picked up. */
    @Test
    public void overwritesAStaleCopyFromAPreviousRun() throws Exception {
        File baseTra = tmp.newFile("bwengine.tra");
        TraFile.write(baseTra, BWENGINE_TRA);
        File out = new File(tmp.newFolder("target2"), ".TIBCO/bwengine.tra");
        assertTrue(out.getParentFile().mkdirs());
        TraFile.write(out, Arrays.asList("tibco.env.TIB_HOME=/opt/old-install"));

        new RunBwMojo().prepareEngineTra(baseTra, out);

        assertEquals(BWENGINE_TRA, TraFile.read(out));
    }
}
