package com.tibco.bw.maven.plugin.packaging;

import com.tibco.bw.maven.plugin.tra.TraFile;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

/**
 * Tests for the project-local {@code bwengine.tra} generated by {@code bw5:run}, and for the
 * classpath entries injected into it.
 *
 * <p>The engine is launched with {@code --propFile target/.TIBCO/bwengine.tra} so the project can
 * adjust launcher settings without writing to the TIBCO installation. The installation is often
 * shared and read-only, so the goal must also keep working when no {@code bwengine.tra} can be
 * found next to the engine binary: before this feature the goal warned and started the engine
 * anyway, and it still has to.</p>
 *
 * <p>{@code tibco.alias.*} entries only resolve projlib and resource references; Java classes have
 * to be on the JVM classpath the launcher builds from {@code CUSTOM_EXT_PREPEND_CP} and
 * {@code CUSTOM_EXT_APPEND_CP}. Which of the two is used decides whether project dependencies win
 * or lose against the TIBCO hotfix, bouncycastle and Rendezvous entries, so the selection is
 * covered here as well.</p>
 */
public class RunBwMojoTraTest {

    @Rule
    public TemporaryFolder tmp = new TemporaryFolder();

    private static final String ENGINE_CP = "tibco.env.CUSTOM_EXT_PREPEND_CP";
    private static final List<String> NO_CP = Collections.emptyList();

    private static final List<String> BWENGINE_TRA = Arrays.asList(
        "# bwengine.tra",
        "tibco.env.TIB_HOME=/opt/tibco",
        "tibco.env.CUSTOM_EXT_PREPEND_CP=/opt/tibco/bw/5.16/hotfix/lib",
        "tibco.class.path.extended %CUSTOM_EXT_PREPEND_CP%:%STD_EXT_CP%");

    @Test
    public void copiesTheInstalledTraToTheBuildDirectory() throws Exception {
        File baseTra = tmp.newFile("bwengine.tra");
        TraFile.write(baseTra, BWENGINE_TRA);
        File out = new File(tmp.newFolder("target"), ".TIBCO/bwengine.tra");

        File generated = new RunBwMojo().prepareEngineTra(baseTra, out, ENGINE_CP, NO_CP, null);

        assertNotNull("a copy must be generated when the installed tra exists", generated);
        assertEquals(out, generated);
        assertTrue("the copy must be written to disk", out.isFile());
        assertEquals("the copy must preserve the installed tra verbatim",
            BWENGINE_TRA, TraFile.read(out));
    }

    @Test
    public void createsTheTargetDirectoryWhenMissing() throws Exception {
        File baseTra = tmp.newFile("bwengine.tra");
        TraFile.write(baseTra, BWENGINE_TRA);
        File out = new File(tmp.getRoot(), "target/.TIBCO/bwengine.tra");
        assertFalse(out.getParentFile().exists());

        assertNotNull(new RunBwMojo().prepareEngineTra(baseTra, out, ENGINE_CP, NO_CP, null));
        assertTrue(out.isFile());
    }

    /**
     * Degrading gracefully matters: the goal must not start failing on installations that have no
     * bwengine.tra next to the binary, which used to warn and run with the engine defaults.
     */
    @Test
    public void returnsNullAndWritesNothingWhenTheInstalledTraIsMissing() throws Exception {
        File baseTra = new File(tmp.getRoot(), "no-such-bwengine.tra");
        File out = new File(tmp.getRoot(), "target/.TIBCO/bwengine.tra");

        assertNull(new RunBwMojo().prepareEngineTra(baseTra, out, ENGINE_CP, NO_CP, null));
        assertFalse("nothing may be written when there is no source tra", out.exists());
    }

    /** A stale copy from a previous run must be replaced, so installation hotfixes are picked up. */
    @Test
    public void overwritesAStaleCopyFromAPreviousRun() throws Exception {
        File baseTra = tmp.newFile("bwengine.tra");
        TraFile.write(baseTra, BWENGINE_TRA);
        File out = new File(tmp.newFolder("target2"), ".TIBCO/bwengine.tra");
        assertTrue(out.getParentFile().mkdirs());
        TraFile.write(out, Arrays.asList("tibco.env.TIB_HOME=/opt/old-install"));

        new RunBwMojo().prepareEngineTra(baseTra, out, ENGINE_CP, NO_CP, null);

        assertEquals(BWENGINE_TRA, TraFile.read(out));
    }

    // -----------------------------------------------------------------------
    //  Classpath injection into the generated copy
    // -----------------------------------------------------------------------

    @Test
    public void injectsTheClasspathEntriesIntoTheGeneratedCopy() throws Exception {
        File baseTra = tmp.newFile("bwengine.tra");
        TraFile.write(baseTra, BWENGINE_TRA);
        File out = new File(tmp.newFolder("t3"), ".TIBCO/bwengine.tra");

        new RunBwMojo().prepareEngineTra(baseTra, out, ENGINE_CP,
            Arrays.asList("/proj/target/bw-lib"), null);

        List<String> written = TraFile.read(out);
        assertEquals("no line may be added or dropped", BWENGINE_TRA.size(), written.size());
        assertEquals("tibco.env.CUSTOM_EXT_PREPEND_CP=/proj/target/bw-lib"
            + File.pathSeparator + "/opt/tibco/bw/5.16/hotfix/lib", written.get(2));
        assertEquals("the installed file must not be touched", BWENGINE_TRA, TraFile.read(baseTra));
    }

    /** {@code append} must land in the other variable, leaving the prepend one alone. */
    @Test
    public void appendModeWritesToTheAppendVariable() throws Exception {
        File baseTra = tmp.newFile("bwengine.tra");
        TraFile.write(baseTra, BWENGINE_TRA);
        File out = new File(tmp.newFolder("t4"), ".TIBCO/bwengine.tra");

        new RunBwMojo().prepareEngineTra(baseTra, out, "tibco.env.CUSTOM_EXT_APPEND_CP",
            Arrays.asList("/m2/a.jar"), null);

        List<String> written = TraFile.read(out);
        assertEquals("the prepend entry must stay untouched",
            "tibco.env.CUSTOM_EXT_PREPEND_CP=/opt/tibco/bw/5.16/hotfix/lib", written.get(2));
        assertEquals("tibco.env.CUSTOM_EXT_APPEND_CP=/m2/a.jar", written.get(4));
    }

    // -----------------------------------------------------------------------
    //  user.home redirection (bw5.run.projectUserHome)
    // -----------------------------------------------------------------------

    /** Off by default: the engine must keep seeing the developer's real home directory. */
    @Test
    public void userHomeIsLeftAloneWhenNotRequested() throws Exception {
        File baseTra = tmp.newFile("bwengine.tra");
        TraFile.write(baseTra, BWENGINE_TRA);
        File out = new File(tmp.newFolder("t5"), ".TIBCO/bwengine.tra");

        new RunBwMojo().prepareEngineTra(baseTra, out, ENGINE_CP, NO_CP, null);

        assertEquals("no user.home entry may be added", BWENGINE_TRA, TraFile.read(out));
    }

    @Test
    public void userHomeIsWrittenIntoTheGeneratedCopyWhenRequested() throws Exception {
        File baseTra = tmp.newFile("bwengine.tra");
        TraFile.write(baseTra, BWENGINE_TRA);
        File out = new File(tmp.newFolder("t6"), ".TIBCO/bwengine.tra");

        new RunBwMojo().prepareEngineTra(baseTra, out, ENGINE_CP, NO_CP, "/proj/target");

        List<String> written = TraFile.read(out);
        assertEquals(BWENGINE_TRA.size() + 1, written.size());
        assertTrue(written.toString(), written.contains("java.property.user.home /proj/target"));
    }

    /** An existing entry must be replaced, not duplicated — the launcher would read the first. */
    @Test
    public void userHomeReplacesAnExistingEntry() throws Exception {
        File baseTra = tmp.newFile("bwengine.tra");
        TraFile.write(baseTra, Arrays.asList(
            "tibco.env.TIB_HOME=/opt/tibco",
            "java.property.user.home=/home/dev"));
        File out = new File(tmp.newFolder("t7"), ".TIBCO/bwengine.tra");

        new RunBwMojo().prepareEngineTra(baseTra, out, ENGINE_CP, NO_CP, "/proj/target");

        assertEquals(Arrays.asList(
            "tibco.env.TIB_HOME=/opt/tibco",
            "java.property.user.home=/proj/target"), TraFile.read(out));
    }

    /** A Windows build directory must survive the launcher's properties-style un-escaping. */
    @Test
    public void userHomeEscapesAWindowsBuildDirectory() throws Exception {
        File baseTra = tmp.newFile("bwengine.tra");
        TraFile.write(baseTra, BWENGINE_TRA);
        File out = new File(tmp.newFolder("t8"), ".TIBCO/bwengine.tra");

        new RunBwMojo().prepareEngineTra(baseTra, out, ENGINE_CP, NO_CP, "C:\\dev\\proj\\target");

        assertTrue(TraFile.read(out).toString(),
            TraFile.read(out).contains("java.property.user.home C:\\\\dev\\\\proj\\\\target"));
    }

    // -----------------------------------------------------------------------
    //  classpathPosition -> TRA variable
    // -----------------------------------------------------------------------

    @Test
    public void classpathPositionSelectsTheTraVariable() throws Exception {
        assertEquals("tibco.env.CUSTOM_EXT_PREPEND_CP", RunBwMojo.engineClasspathKey("prepend"));
        assertEquals("tibco.env.CUSTOM_EXT_APPEND_CP", RunBwMojo.engineClasspathKey("append"));
        assertEquals("the value must not be case sensitive",
            "tibco.env.CUSTOM_EXT_APPEND_CP", RunBwMojo.engineClasspathKey("APPEND"));
    }

    /** A typo must fail the build rather than silently fall back to a default. */
    @Test
    public void classpathPositionRejectsAnUnknownValue() {
        try {
            RunBwMojo.engineClasspathKey("front");
            fail("an unknown classpathPosition must be rejected");
        } catch (Exception e) {
            assertTrue(e.getMessage(), e.getMessage().contains("bw5.run.classpathPosition"));
        }
    }

    // -----------------------------------------------------------------------
    //  classpathMode -> entries
    // -----------------------------------------------------------------------

    private static final List<String> JARS = Arrays.asList("/m2/a-1.0.jar", "/m2/b-2.0.jar");

    /** The opt-out: bw5:run then behaves exactly as it did before this parameter existed. */
    @Test
    public void classpathModeNoneAddsNothing() throws Exception {
        assertTrue(RunBwMojo.classpathEntries("none", "/proj/target/bw-lib", JARS).isEmpty());
    }

    /** One entry, not one per jar: the TRA launcher expands a directory into the JARs it holds. */
    @Test
    public void classpathModeLibDirAddsTheStagingDirectoryOnly() throws Exception {
        assertEquals(Arrays.asList("/proj/target/bw-lib"),
            RunBwMojo.classpathEntries("libDir", "/proj/target/bw-lib", JARS));
    }

    /** Without the staging step there is no directory to add; adding a missing path breaks nothing
     *  but hides the real problem, so the mode must degrade to adding nothing. */
    @Test
    public void classpathModeLibDirAddsNothingWhenTheDirectoryIsMissing() throws Exception {
        assertTrue(RunBwMojo.classpathEntries("libDir", null, JARS).isEmpty());
    }

    @Test
    public void classpathModeDependenciesAddsEveryResolvedJar() throws Exception {
        assertEquals(JARS, RunBwMojo.classpathEntries("dependencies", "/proj/target/bw-lib", JARS));
    }

    @Test
    public void classpathModeRejectsAnUnknownValue() {
        try {
            RunBwMojo.classpathEntries("all", null, JARS);
            fail("an unknown classpathMode must be rejected");
        } catch (Exception e) {
            assertTrue(e.getMessage(), e.getMessage().contains("bw5.run.classpathMode"));
        }
    }

    /**
     * The defaults are asserted against the generated plugin descriptor rather than the
     * {@code @Parameter} annotation, which is compiled with {@code RetentionPolicy.CLASS} and is
     * therefore invisible to reflection. The descriptor is what Maven actually reads, so this is
     * also the more faithful check.
     */
    private static String descriptorDefault(String parameterName) throws IOException {
        InputStream in = RunBwMojoTraTest.class.getResourceAsStream("/META-INF/maven/plugin.xml");
        assertNotNull("plugin.xml is generated at process-classes — run this through Maven", in);
        String xml;
        try {
            xml = new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } finally {
            in.close();
        }
        Matcher m = Pattern.compile("<" + parameterName + " [^>]*default-value=\"([^\"]*)\"")
            .matcher(xml);
        assertTrue(parameterName + " must keep a default-value in the plugin descriptor", m.find());
        return m.group(1);
    }

    /**
     * The default must be {@code libDir}. With {@code none}, a project whose Java activities or
     * custom functions come from Maven dependencies dies with a {@code ClassNotFoundException} as
     * soon as a process reaches one — reproduced on a real project, where the engine could not get
     * past its first global instance until {@code target/bw-lib} was on the classpath.
     */
    @Test
    public void classpathModeDefaultsToLibDir() throws Exception {
        assertEquals(RunBwMojo.CP_MODE_LIB_DIR, descriptorDefault("classpathMode"));
    }

    /** Prepending keeps the project's own versions ahead of the ones the installation ships. */
    @Test
    public void classpathPositionDefaultsToPrepend() throws Exception {
        assertEquals(RunBwMojo.CP_POSITION_PREPEND, descriptorDefault("classpathPosition"));
    }
}
