package com.tibco.bw.maven.plugin.descriptor;

import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.Namespace;
import org.jdom2.input.SAXBuilder;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 * Parses a TIBCO BusinessWorks 5 {@code .archive} descriptor file.
 *
 * <p>The {@code .archive} file is generated by TIBCO Designer's Archive Builder
 * and describes the structure of an Enterprise Archive (EAR): which Process
 * Archives and Adapter Archives it contains, which processes go in each, and
 * how the Shared Archive is named.</p>
 *
 * <p>Single-PAR example:</p>
 * <pre>
 * &lt;Repository:repository xmlns:Repository="http://www.tibco.com/xmlns/repo/types/2002"&gt;
 *   &lt;enterpriseArchive&gt;
 *     &lt;name&gt;MyApp&lt;/name&gt;
 *     &lt;processArchive name="Process Archive"&gt;
 *       &lt;processProperty&gt;/MyApp/Start.process,/MyApp/Sub.process&lt;/processProperty&gt;
 *     &lt;/processArchive&gt;
 *     &lt;sharedArchive name="Shared Archive"/&gt;
 *   &lt;/enterpriseArchive&gt;
 * &lt;/Repository:repository&gt;
 * </pre>
 *
 * <p>Multi-PAR and Adapter Archive example:</p>
 * <pre>
 * &lt;enterpriseArchive&gt;
 *   &lt;name&gt;MyApp&lt;/name&gt;
 *   &lt;processArchive name="OrderService"&gt;
 *     &lt;processProperty&gt;/Services/Order/ReceiveOrder.process&lt;/processProperty&gt;
 *   &lt;/processArchive&gt;
 *   &lt;processArchive name="PaymentService"&gt;
 *     &lt;processProperty&gt;/Services/Payment/ProcessPayment.process&lt;/processProperty&gt;
 *   &lt;/processArchive&gt;
 *   &lt;adapterArchive name="SalesforceAdapter"&gt;
 *     &lt;processProperty&gt;/Adapters/SalesforceService.serviceagent&lt;/processProperty&gt;
 *   &lt;/adapterArchive&gt;
 *   &lt;sharedArchive name="Shared Archive"/&gt;
 * &lt;/enterpriseArchive&gt;
 * </pre>
 */
public class ArchiveDescriptorParser {

    private static final Namespace REPO_NS =
        Namespace.getNamespace("Repository", "http://www.tibco.com/xmlns/repo/types/2002");

    private static final Namespace REPO_NS_DEFAULT =
        Namespace.getNamespace("http://www.tibco.com/xmlns/repo/types/2002");

    /** Namespace used by the TIBCO Designer archivedefn format. */
    private static final Namespace ARCHIVEDEFN_NS =
        Namespace.getNamespace("http://xmlns.tibco.com/bw/archivedefn");

    /**
     * Parses the {@code .archive} descriptor and returns its metadata.
     *
     * <p>Two XML formats are supported:</p>
     * <ul>
     *   <li><b>Repository format</b> — root is {@code Repository:repository} or bare
     *       {@code repository}; entry points listed in {@code <processProperty>} CSV text.</li>
     *   <li><b>Archivedefn format</b> — root is {@code aa:archive}
     *       (namespace {@code http://xmlns.tibco.com/bw/archivedefn}); entry points are
     *       {@code <aa:processStart name="..."/>} attributes.</li>
     * </ul>
     *
     * @param archiveFile the {@code .archive} file to parse
     * @return parsed archive descriptor metadata
     * @throws Exception if the file cannot be parsed
     */
    public ArchiveDescriptor parse(File archiveFile) throws Exception {
        SAXBuilder builder = new SAXBuilder();
        Document doc = builder.build(archiveFile);
        Element root = doc.getRootElement();

        // Dispatch to format-specific parser
        Namespace rootNs = root.getNamespace();
        if (ARCHIVEDEFN_NS.getURI().equals(rootNs.getURI())
                || "archive".equals(root.getName())) {
            return parseArchivedefnFormat(root);
        }
        return parseRepositoryFormat(root);
    }

    /**
     * Parses the archivedefn format:
     * <pre>
     * &lt;aa:archive name="MyApp" xmlns:aa="http://xmlns.tibco.com/bw/archivedefn"&gt;
     *   &lt;aa:processStart name="/Services/Main.process" enabled="true"/&gt;
     * &lt;/aa:archive&gt;
     * </pre>
     */
    private ArchiveDescriptor parseArchivedefnFormat(Element root) {
        ArchiveDescriptor descriptor = new ArchiveDescriptor();
        descriptor.earName = root.getAttributeValue("name");

        ProcessArchiveEntry entry = new ProcessArchiveEntry();
        entry.name = descriptor.earName;

        for (Element child : root.getChildren()) {
            String localName = child.getName();
            if ("processStart".equals(localName)) {
                String path = child.getAttributeValue("name");
                if (path != null && !path.isEmpty()) {
                    entry.processPaths.add(path);
                }
            }
        }
        descriptor.processArchives.add(entry);
        return descriptor;
    }

    /**
     * Parses the legacy Repository format:
     * <pre>
     * &lt;Repository:repository xmlns:Repository="http://www.tibco.com/xmlns/repo/types/2002"&gt;
     *   &lt;enterpriseArchive&gt;
     *     &lt;processArchive name="Process Archive"&gt;
     *       &lt;processProperty&gt;/MyApp/Start.process&lt;/processProperty&gt;
     *     &lt;/processArchive&gt;
     *   &lt;/enterpriseArchive&gt;
     * &lt;/Repository:repository&gt;
     * </pre>
     */
    private ArchiveDescriptor parseRepositoryFormat(Element root) {
        ArchiveDescriptor descriptor = new ArchiveDescriptor();

        Element enterpriseArchive = getChildNoNs(root, "enterpriseArchive");
        if (enterpriseArchive == null) {
            return descriptor;
        }

        descriptor.earName = getTextNoNs(enterpriseArchive, "name");
        descriptor.version = getTextNoNs(enterpriseArchive, "versionProperty");

        // All <processArchive> elements (multi-PAR support)
        for (Element pa : getChildrenNoNs(enterpriseArchive, "processArchive")) {
            ProcessArchiveEntry entry = new ProcessArchiveEntry();
            entry.name = pa.getAttributeValue("name");
            String processPropertyText = getTextNoNs(pa, "processProperty");
            if (processPropertyText != null && !processPropertyText.isBlank()) {
                for (String rawPath : processPropertyText.split(",")) {
                    String path = rawPath.trim();
                    if (!path.isEmpty()) entry.processPaths.add(path);
                }
            }
            descriptor.processArchives.add(entry);
        }

        // All <adapterArchive> elements (AAR support)
        for (Element aa : getChildrenNoNs(enterpriseArchive, "adapterArchive")) {
            AdapterArchiveEntry entry = new AdapterArchiveEntry();
            entry.name = aa.getAttributeValue("name");
            entry.adapterReference = getTextNoNs(aa, "adapterReference");
            entry.sdkVersion = getTextNoNs(aa, "sdkVersion");
            entry.softwareType = getTextNoNs(aa, "softwareTypeProperty");
            descriptor.adapterArchives.add(entry);
        }

        // <sharedArchive>
        Element sharedArchive = getChildNoNs(enterpriseArchive, "sharedArchive");
        if (sharedArchive != null) {
            descriptor.sharedArchiveName = sharedArchive.getAttributeValue("name");
            String sharedResourcesText = getTextNoNs(sharedArchive, "sharedResources");
            if (sharedResourcesText != null && !sharedResourcesText.isBlank()) {
                for (String rawPath : sharedResourcesText.split(",")) {
                    String path = rawPath.trim();
                    if (!path.isEmpty()) descriptor.sharedResourcePaths.add(path);
                }
            }
        }

        return descriptor;
    }

    private Element getChildNoNs(Element parent, String localName) {
        Element child = parent.getChild(localName);
        if (child != null) return child;
        child = parent.getChild(localName, REPO_NS_DEFAULT);
        if (child != null) return child;
        return parent.getChild(localName, REPO_NS);
    }

    private List<Element> getChildrenNoNs(Element parent, String localName) {
        List<Element> result = new ArrayList<>();
        result.addAll(parent.getChildren(localName));
        result.addAll(parent.getChildren(localName, REPO_NS_DEFAULT));
        result.addAll(parent.getChildren(localName, REPO_NS));
        return result;
    }

    private String getTextNoNs(Element parent, String localName) {
        Element child = getChildNoNs(parent, localName);
        return child != null ? child.getTextTrim() : null;
    }

    // -----------------------------------------------------------------------
    //  Data model
    // -----------------------------------------------------------------------

    /** One {@code <processArchive>} element from the descriptor. */
    public static class ProcessArchiveEntry {
        /** Archive name from {@code processArchive/@name} — becomes the PAR filename. */
        public String name;
        /** Entry-point process paths from {@code processProperty}. */
        public List<String> processPaths = new ArrayList<>();

        public boolean hasExplicitProcessList() { return !processPaths.isEmpty(); }
    }

    /** One {@code <adapterArchive>} element from the descriptor. */
    public static class AdapterArchiveEntry {
        /** Archive name from {@code adapterArchive/@name} — becomes the AAR filename. */
        public String name;
        /**
         * Raw value of {@code <adapterReference>}, e.g.
         * {@code /path/to/Foo.adapter#adapter.GenericAdapterConfiguration}.
         */
        public String adapterReference;
        /** SDK version from {@code <sdkVersion>}, e.g. {@code 5.3.0}. */
        public String sdkVersion;
        /**
         * Adapter component software type from {@code <softwareTypeProperty>}
         * (e.g. {@code adb}, {@code adr3}). Determines the {@code componentSoftwareName}
         * and which bundled deployment resource supplies the Adapter SDK Properties.
         */
        public String softwareType;

        /**
         * BW path of the {@code .adapter} file — {@code adapterReference} with the
         * {@code #...} fragment stripped and the leading {@code /} removed.
         * Returns {@code null} when {@code adapterReference} is null.
         */
        public String getAdapterFilePath() {
            if (adapterReference == null) return null;
            String path = adapterReference;
            int hash = path.indexOf('#');
            if (hash >= 0) path = path.substring(0, hash);
            return path.startsWith("/") ? path.substring(1) : path;
        }

        /** Minimum/config SDK version as a 4-part string, e.g. {@code 5.3.0} → {@code 5.3.0.0}. */
        @SuppressWarnings("PMD.AvoidUsingHardCodedIP")
        public String getSdkVersionFourPart() {
            if (sdkVersion == null || sdkVersion.isEmpty()) return "5.0.0.0";
            long dots = sdkVersion.chars().filter(c -> c == '.').count();
            return dots >= 3 ? sdkVersion : sdkVersion + ".0";
        }
    }

    /**
     * Metadata extracted from a {@code .archive} descriptor file.
     */
    public static class ArchiveDescriptor {
        /** EAR archive name from {@code enterpriseArchive/name}. */
        public String earName;
        /**
         * Archive version from {@code enterpriseArchive/versionProperty} (e.g. {@code 2}, {@code 8}).
         * buildear stamps this same value into the {@code <version>} of the EAR, every PAR and
         * every AAR TIBCO.xml. {@code null} when the descriptor omits it.
         */
        public String version;
        /** Name of the Shared Archive (SAR), from {@code sharedArchive/@name}. */
        public String sharedArchiveName;
        /** All {@code <processArchive>} elements — one entry per PAR. */
        public List<ProcessArchiveEntry> processArchives = new ArrayList<>();
        /** All {@code <adapterArchive>} elements — one entry per AAR. */
        public List<AdapterArchiveEntry> adapterArchives = new ArrayList<>();
        /**
         * Explicit shared-resource directory paths from {@code sharedArchive/sharedResources}.
         * buildear includes ALL files under these BW paths in the SAR unconditionally.
         */
        public List<String> sharedResourcePaths = new ArrayList<>();

        // ---- Convenience accessors for single-PAR callers (first processArchive) ----

        /** Name of the first (or only) Process Archive. {@code null} if none declared. */
        public String getProcessArchiveName() {
            return processArchives.isEmpty() ? null : processArchives.get(0).name;
        }

        /** Entry-point paths of the first Process Archive. Empty if none declared. */
        public List<String> getProcessPaths() {
            return processArchives.isEmpty() ? new ArrayList<>() : processArchives.get(0).processPaths;
        }

        /** Returns {@code true} if any process archive has an explicit process list. */
        public boolean hasExplicitProcessList() {
            for (ProcessArchiveEntry e : processArchives) {
                if (e.hasExplicitProcessList()) return true;
            }
            return false;
        }

        /** Returns {@code true} if this descriptor defines more than one PAR. */
        public boolean isMultiPar() {
            return processArchives.size() > 1;
        }

        /** Returns {@code true} if this descriptor defines at least one AAR. */
        public boolean hasAdapterArchives() {
            return !adapterArchives.isEmpty();
        }

        @Override
        public String toString() {
            return "ArchiveDescriptor{earName=" + earName
                + ", pars=" + processArchives.size()
                + ", aars=" + adapterArchives.size()
                + ", sar=" + sharedArchiveName
                + ", sharedResources=" + sharedResourcePaths + "}";
        }
    }
}
