package com.tibco.bw.maven.plugin.descriptor;

import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.Namespace;
import org.jdom2.input.SAXBuilder;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 * Parses a TIBCO BusinessWorks 5 {@code .archive} descriptor file.
 *
 * <p>The {@code .archive} file is generated by TIBCO Designer's Archive Builder
 * and describes the structure of an Enterprise Archive (EAR):
 * which Process Archive it builds, which processes go in it, and how the
 * Shared Archive is named. Shared resource files are NOT listed explicitly —
 * {@code buildEAR} (and this plugin) scan the project for all recognised
 * shared-resource types.</p>
 *
 * <p>Example {@code .archive} file structure:</p>
 * <pre>
 * &lt;Repository:repository xmlns:Repository="http://www.tibco.com/xmlns/repo/types/2002"&gt;
 *   &lt;enterpriseArchive&gt;
 *     &lt;name&gt;MyApp&lt;/name&gt;
 *     &lt;processArchive name="Process Archive"&gt;
 *       &lt;processProperty&gt;/MyApp/Start.process,/MyApp/Sub.process&lt;/processProperty&gt;
 *     &lt;/processArchive&gt;
 *     &lt;sharedArchive name="Shared Archive"&gt;
 *       ...
 *     &lt;/sharedArchive&gt;
 *     &lt;fileLocationProperty&gt;C:\out\MyApp.ear&lt;/fileLocationProperty&gt;
 *   &lt;/enterpriseArchive&gt;
 * &lt;/Repository:repository&gt;
 * </pre>
 */
public class ArchiveDescriptorParser {

    private static final Namespace REPO_NS =
        Namespace.getNamespace("Repository", "http://www.tibco.com/xmlns/repo/types/2002");

    /** Namespace without prefix (element content may use default namespace) */
    private static final Namespace REPO_NS_DEFAULT =
        Namespace.getNamespace("http://www.tibco.com/xmlns/repo/types/2002");

    /**
     * Parses the {@code .archive} descriptor and returns its metadata.
     *
     * @param archiveFile the {@code .archive} file to parse
     * @return parsed archive descriptor metadata
     * @throws Exception if the file cannot be parsed
     */
    public ArchiveDescriptor parse(File archiveFile) throws Exception {
        SAXBuilder builder = new SAXBuilder();
        Document doc = builder.build(archiveFile);
        Element root = doc.getRootElement();

        // Root element is repository (possibly prefixed)
        ArchiveDescriptor descriptor = new ArchiveDescriptor();

        // Find the enterpriseArchive child (no namespace on child elements in this format)
        Element enterpriseArchive = getChildNoNs(root, "enterpriseArchive");
        if (enterpriseArchive == null) {
            return descriptor;
        }

        // EAR name from <name> inside enterpriseArchive
        descriptor.earName = getTextNoNs(enterpriseArchive, "name");

        // Process archive
        Element processArchive = getChildNoNs(enterpriseArchive, "processArchive");
        if (processArchive != null) {
            descriptor.processArchiveName = processArchive.getAttributeValue("name");
            String processPropertyText = getTextNoNs(processArchive, "processProperty");
            if (processPropertyText != null && !processPropertyText.isBlank()) {
                for (String rawPath : processPropertyText.split(",")) {
                    String path = rawPath.trim();
                    if (!path.isEmpty()) {
                        descriptor.processPaths.add(path);
                    }
                }
            }
        }

        // Shared archive
        Element sharedArchive = getChildNoNs(enterpriseArchive, "sharedArchive");
        if (sharedArchive != null) {
            descriptor.sharedArchiveName = sharedArchive.getAttributeValue("name");
            // sharedResources: comma-separated list of BW paths explicitly added to the SAR
            // by buildear regardless of transitive reachability (e.g. "/CommonCore/SharedResources/Schemas,/config_ear")
            String sharedResourcesText = getTextNoNs(sharedArchive, "sharedResources");
            if (sharedResourcesText != null && !sharedResourcesText.isBlank()) {
                for (String rawPath : sharedResourcesText.split(",")) {
                    String path = rawPath.trim();
                    if (!path.isEmpty()) {
                        descriptor.sharedResourcePaths.add(path);
                    }
                }
            }
        }

        return descriptor;
    }

    private Element getChildNoNs(Element parent, String localName) {
        // Try no-namespace first (most common in .archive files)
        Element child = parent.getChild(localName);
        if (child != null) return child;
        // Try with the repository namespace
        child = parent.getChild(localName, REPO_NS_DEFAULT);
        if (child != null) return child;
        return parent.getChild(localName, REPO_NS);
    }

    private String getTextNoNs(Element parent, String localName) {
        Element child = getChildNoNs(parent, localName);
        return child != null ? child.getTextTrim() : null;
    }

    /**
     * Metadata extracted from a {@code .archive} descriptor file.
     */
    public static class ArchiveDescriptor {
        /** EAR archive name from {@code enterpriseArchive/name} */
        public String earName;
        /** Name of the Process Archive (PAR), from {@code processArchive/@name} */
        public String processArchiveName;
        /** Name of the Shared Archive (SAR), from {@code sharedArchive/@name} */
        public String sharedArchiveName;
        /**
         * Explicit list of process paths from {@code processArchive/processProperty}.
         * Each path starts with {@code /} (e.g. {@code /MyApp/Start.process}).
         * When empty, all {@code .process} files in the project are included.
         */
        public List<String> processPaths = new ArrayList<>();

        /**
         * Explicit shared-resource directory paths from {@code sharedArchive/sharedResources}.
         * buildear includes ALL files under these BW paths in the SAR unconditionally,
         * regardless of whether they are transitively reachable from any process.
         * Example: {@code ["/CommonCore/SharedResources/Schemas", "/config_ear"]}.
         */
        public List<String> sharedResourcePaths = new ArrayList<>();

        /** Returns true if an explicit process list is defined in the descriptor. */
        public boolean hasExplicitProcessList() {
            return !processPaths.isEmpty();
        }

        @Override
        public String toString() {
            return "ArchiveDescriptor{earName=" + earName
                + ", par=" + processArchiveName
                + ", sar=" + sharedArchiveName
                + ", processes=" + processPaths
                + ", sharedResources=" + sharedResourcePaths + "}";
        }
    }
}
