package com.tibco.bw.maven.plugin.descriptor;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Parses a TIBCO Designer {@code .designtimelibs} file.
 *
 * <p>The {@code .designtimelibs} file is maintained by TIBCO Designer and lists the projlib
 * files registered for a project. Two line formats are supported:</p>
 * <ul>
 *   <li>Bare path: {@code /opt/tibco/libs/FrameworkCommon.projlib}</li>
 *   <li>Numbered entry generated by Designer: {@code 1=/opt/tibco/libs/FrameworkCommon.projlib}</li>
 * </ul>
 *
 * <p>Lines starting with {@code #} and blank lines are ignored.</p>
 */
public class DesignTimeLibsParser {

    /**
     * Parses the {@code .designtimelibs} file and returns the raw projlib paths it contains.
     *
     * @param file the {@code .designtimelibs} file to parse
     * @return list of raw file paths (may be absolute paths on the original developer machine)
     * @throws IOException if the file cannot be read
     */
    public List<String> parse(File file) throws IOException {
        List<String> paths = new ArrayList<>();
        try (BufferedReader reader = new BufferedReader(
                new InputStreamReader(java.nio.file.Files.newInputStream(file.toPath()), StandardCharsets.UTF_8))) {
            String line;
            while ((line = reader.readLine()) != null) {
                line = line.trim();
                if (line.isEmpty() || line.startsWith("#")) {
                    continue;
                }
                // Handle "N=<path>" or "N=<path>=<description>" numbered format
                if (line.matches("\\d+=.*")) {
                    line = line.substring(line.indexOf('=') + 1).trim();
                }
                // Strip "=description" suffix written by Designer (e.g. "/lib.projlib=My Library").
                // Maven coordinates produced by bw5:designer-setup end with "\=" (escaped equals)
                // whose preceding char is '\', so the unescaped-equals scan leaves them intact.
                line = stripDesignerDescription(line);
                if (!line.isEmpty()) {
                    paths.add(line);
                }
            }
        }
        return paths;
    }

    /**
     * Strips the {@code =description} suffix that TIBCO Designer appends to each entry
     * ({@code filepath=Human Readable Name}).
     *
     * <p>Scans for the first {@code =} that is NOT preceded by a backslash (unescaped).
     * Maven coordinates written by {@code bw5:designer-setup} end with {@code \=} (backslash
     * before the equals), so they pass through unchanged.</p>
     */
    static String stripDesignerDescription(String value) {
        for (int i = 0; i < value.length(); i++) {
            if (value.charAt(i) == '=' && (i == 0 || value.charAt(i - 1) != '\\')) {
                return value.substring(0, i).trim();
            }
        }
        return value;
    }

    /**
     * Extracts the library name from a projlib file path.
     *
     * <p>Returns the filename without directory path and without the {@code .projlib}
     * extension (case-insensitive). Works with both Unix and Windows path separators.</p>
     *
     * <p>Examples:</p>
     * <ul>
     *   <li>{@code /opt/tibco/libs/FrameworkCommon.projlib} → {@code FrameworkCommon}</li>
     *   <li>{@code C:\tibco\libs\AnotherLib.projlib} → {@code AnotherLib}</li>
     *   <li>{@code MyLib.projlib} → {@code MyLib}</li>
     * </ul>
     *
     * @param libPath raw path from the {@code .designtimelibs} file
     * @return library name (filename without path and without {@code .projlib} extension)
     */
    public static String extractLibName(String libPath) {
        // Handle Maven coordinate format written by bw5:designer-setup:
        // after DesignTimeLibsParser.parse() strips the "N=" prefix, the value is
        // "groupId\:artifactId\:version\:type\=" (escaped colons, trailing \=).
        // Detect this format before treating the string as a file path — otherwise
        // replace('\\', '/') turns \: into /: and lastIndexOf('/') picks up the = sign.
        String stripped = libPath;
        if (stripped.endsWith("\\=")) {
            stripped = stripped.substring(0, stripped.length() - 2);
        }
        String unescaped = stripped.replace("\\:", ":");
        // Maven coordinate: groupId:artifactId:version[:type] — at least 3 colon-separated parts.
        // A Windows drive letter (e.g. "C:\path") also contains ":" but has only one.
        String[] parts = unescaped.split(":", -1);
        if (parts.length >= 3) {
            return parts[1];
        }

        // File path format (e.g. /opt/tibco/libs/FrameworkCommon.projlib)
        String name = libPath.replace('\\', '/');
        int slash = name.lastIndexOf('/');
        if (slash >= 0) {
            name = name.substring(slash + 1);
        }
        if (name.toLowerCase(Locale.ROOT).endsWith(".projlib")) {
            name = name.substring(0, name.length() - ".projlib".length());
        }
        return name;
    }
}
