package com.tibco.bw.maven.plugin.descriptor;

import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.Namespace;
import org.jdom2.input.SAXBuilder;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 * Parses a TIBCO BusinessWorks 5 {@code .libbuilder} descriptor file.
 *
 * <p>The {@code .libbuilder} file is generated by TIBCO Designer's Library Builder
 * and specifies which processes and shared resources are exported into the projlib.
 * It is the projlib equivalent of the {@code .archive} file for EARs.</p>
 *
 * <p>Example structure:</p>
 * <pre>
 * &lt;Repository:repository xmlns:Repository="http://www.tibco.com/xmlns/repo/types/2002"&gt;
 *   &lt;name name="MyLibrary"&gt;
 *     &lt;version&gt;1&lt;/version&gt;
 *     &lt;fileLocation&gt;/path/to/MyLibrary.projlib&lt;/fileLocation&gt;
 *     &lt;resources&gt;/MyLib/Process1.process,/SharedResources/Conn.sharedjdbc&lt;/resources&gt;
 *   &lt;/name&gt;
 * &lt;/Repository:repository&gt;
 * </pre>
 *
 * <p>The {@code resources} element contains a comma-separated list of absolute paths
 * (relative to the BW project root, starting with {@code /}) of the files to include.
 * {@code .folder} and {@code .substvar} files are not listed explicitly — Designer
 * includes them automatically based on the directory structure.</p>
 */
public class LibBuilderParser {

    private static final Namespace REPO_NS =
        Namespace.getNamespace("Repository", "http://www.tibco.com/xmlns/repo/types/2002");

    private static final Namespace REPO_NS_DEFAULT =
        Namespace.getNamespace("http://www.tibco.com/xmlns/repo/types/2002");

    /**
     * Parses the {@code .libbuilder} descriptor and returns its metadata.
     *
     * @param libBuilderFile the {@code .libbuilder} file to parse
     * @return parsed descriptor metadata
     * @throws Exception if the file cannot be parsed
     */
    public LibBuilderDescriptor parse(File libBuilderFile) throws Exception {
        SAXBuilder builder = new SAXBuilder();
        Document doc = builder.build(libBuilderFile);
        Element root = doc.getRootElement();

        LibBuilderDescriptor descriptor = new LibBuilderDescriptor();

        // <name name="..."> element
        Element nameEl = getChildNoNs(root, "name");
        if (nameEl == null) return descriptor;

        descriptor.libraryName = nameEl.getAttributeValue("name");
        descriptor.version = getTextNoNs(nameEl, "version");
        descriptor.fileLocation = getTextNoNs(nameEl, "fileLocation");

        String resourcesText = getTextNoNs(nameEl, "resources");
        if (resourcesText != null && !resourcesText.isBlank()) {
            for (String rawPath : resourcesText.split(",")) {
                String path = rawPath.trim();
                if (!path.isEmpty()) {
                    // Normalize: strip leading /
                    if (path.startsWith("/")) {
                        path = path.substring(1);
                    }
                    descriptor.resources.add(path);
                }
            }
        }

        return descriptor;
    }

    private Element getChildNoNs(Element parent, String localName) {
        Element child = parent.getChild(localName);
        if (child != null) return child;
        child = parent.getChild(localName, REPO_NS_DEFAULT);
        if (child != null) return child;
        return parent.getChild(localName, REPO_NS);
    }

    private String getTextNoNs(Element parent, String localName) {
        Element child = getChildNoNs(parent, localName);
        return child != null ? child.getTextTrim() : null;
    }

    /**
     * Metadata extracted from a {@code .libbuilder} descriptor file.
     */
    public static class LibBuilderDescriptor {

        /** Library name from {@code name/@name} */
        public String libraryName;

        /** Version string from {@code name/version} */
        public String version;

        /** Absolute output file path from {@code name/fileLocation} */
        public String fileLocation;

        /**
         * Explicit list of resource paths to include in the projlib.
         * Paths are normalized (no leading {@code /}).
         * Includes {@code .process} and shared resource files.
         * {@code .folder} and {@code .substvar} files are handled implicitly by the plugin.
         */
        public List<String> resources = new ArrayList<>();

        /** Returns true if an explicit resource list is defined. */
        public boolean hasExplicitResourceList() {
            return !resources.isEmpty();
        }

        @Override
        public String toString() {
            return "LibBuilderDescriptor{name=" + libraryName
                + ", version=" + version
                + ", resources=" + resources.size() + "}";
        }
    }
}
